[project]
name = "tissue-map-tools"
version = "0.1.0"
description = "Utilities for working with tissue maps and 3D spatial omics in Python, with a focus on mesh processing and visualization."
readme = "README.md"
authors = [
    { name = "Eric Moerth", email = "ericmoerth@g.harvard.edu" },
    { name = "Luca Marconato", email = "luca.marconato@embl.de" }
]
requires-python = ">=3.12"
dependencies = [
    "trimesh",
    "pyfqmr",
    "jupyterlab>=3",
    "ome-types>=0.6.0",
    "ome-zarr>=0.10.3",
    "tifffile>=2025.3.30",
    "cloud-volume>=12.6.3",
    "xarray>=2024.9.0",
    "xmltodict>=1.0.2",
    "vitessce[all]>=3.9.6",
]

[dependency-groups]
extra = [
    # https://github.com/seung-lab/igneous/issues/211#issuecomment-3366714308
    "igneous-pipeline>=4.32.0,!=4.33.0,!=4.34.0",
    "task-queue>=2.14.2",
]
examples = [
    "dirhash>=0.5.0",
    "neuroglancer>=2.41.2",
    "napari-spatialdata>=0.5.5",
    "spatialdata>=0.7.0",
    "napari>=0.6.1",
    "pyqt5>=5.15.11",
    "fiona>=1.10.1",
    "setuptools<81",
    "anndata<0.13",
]
dev = [
    "pre-commit>=4.2.0",
]
test = [
    "pytest"
]

[tool.uv]
default-groups = ["examples", "dev", "test", "extra"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
